name: Setup Gleam
description: Install the Gleam compiler
author: Louis Pilfold <louis@lpil.uk>
branding:
  color: white
  icon: box
inputs:
  gleam-version:
    description: Version of Gleam to install
    required: true
  gleam-cache:
    description: URL template for the x86_64 gleam binary. Substring "VERSION" shall be substituted with gleam-version input
    required: false
runs:
  using: node12
  main: main.js
